-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS functie
(
    id_functie integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    functie character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT id_functie_pk PRIMARY KEY (id_functie)
);

CREATE TABLE IF NOT EXISTS bedrijf
(
    id_bedrijf integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    bedrijfs_naam character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT id_bedrijf_pk PRIMARY KEY (id_bedrijf)
);

CREATE TABLE IF NOT EXISTS gebruiker
(
    id_gebruiker integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    achternaam character varying(255) COLLATE pg_catalog."default" NOT NULL,
    voornaam character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_functie integer NOT NULL,
    id_bedrijf integer NOT NULL,
    ts_create timestamp without time zone NOT NULL,
    CONSTRAINT id_gebruiker_pk PRIMARY KEY (id_gebruiker),
    CONSTRAINT id_functie_fk FOREIGN KEY (id_functie) REFERENCES functie (id_functie),
    CONSTRAINT id_bedrijf_fk FOREIGN KEY (id_bedrijf) REFERENCES bedrijf (id_bedrijf)
);

CREATE INDEX IF NOT EXISTS idx_17941_gst_oe_bron
    ON functie(id_functie);

CREATE INDEX IF NOT EXISTS idx_17941_gst_oe_bron
    ON bedrijf(id_bedrijf);

CREATE INDEX IF NOT EXISTS idx_17941_gst_oe_bron
    ON gebruiker(id_gebruiker);

END;